name: Build

on:
  push:
    branches: '*'
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: '*'
  workflow_call:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
jobs:
  build:
    runs-on: [windows-latest]
    strategy:
      matrix:
        configuration: [Release, WineRelease]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build with dotnet
      working-directory: Elmanager
      run: dotnet publish --configuration ${{ matrix.configuration }}
    - name: Upload Release artifact
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: Elmanager-${{ matrix.configuration }}
        path: Elmanager/bin/${{ matrix.configuration }}/net8.0-windows7.0/win-x64/publish/Elmanager.exe
        compression-level: 9
    - name: Upload WineRelease artifact
      if: matrix.configuration == 'WineRelease'
      uses: actions/upload-artifact@v4
      with:
        name: Elmanager-${{ matrix.configuration }}
        path: Elmanager/bin/${{ matrix.configuration }}/net8.0-windows7.0/win-x64/publish/
        compression-level: 9
